### ISSUE TITLE
'Continues on as' column on schedules table

### ISSUE THREAD

**Issue by andymwta** [whatcomtrans/scheduler#2]
//Select the last valid time in the row (some td have '--' and is not valid for input)
//Put the trip_id for that row into a variable
//Create an array of all trips that match the block_id and direction_id and service_id(?) of the current row
//Compare the last valid time in current trip to the first valid time in the trips in this array
//Closest sequential time should be the continues on as trip
//grab the route_id from this trip
//get the route_name (and headsign?)
//append a td to each tr in table with this value (first should be "continues on as" string)

**Comment by joshn-ridewta-com** [comment]
Some may not continue on in which case the proper answer is "Out of Service".  This would happen if difference in time is greater the 10 minutes?  Continues on as route/direction should hyperlink to that schedule.  In many cases the continues on as will be same route but different direction.

**Comment by andymwta** [comment]
Quick note on continues on as hyperlink- This column, should have an id=trip_id of the continuing trip.
If this trip_id is not currently displayed in the table (check tr id's), look up the trip_id by route (and direction_id and service_id) and call the displaySelectedRoute() function with these arguments. This will redraw the table as needed to take the user to the clicked on trip.
If the trip_id IS in the current table (this is an id of the tr), just do a temporary css highlight of the row or something similar.

**Comment by andymwta** [comment]
This feature is in and working. Performance is a concern on mobile devices as the data model is currently set up. Have used setTimeout intervals to keep browser from freezing while this executes. Do we want to have a separate set of functionality for mobile users that does not execute this until they are able to see this column?
